

Stationary Process: Inflation Rate
```{r}

data(Mishkin, package = "Ecdat")

head(Mishkin)

y = as.ts(Mishkin[,1], start=1950, frequency=12)
y = ts(as.vector(Mishkin[,1]), start=1950, frequency=12)  

par(mfrow=c(2,1))

plot(y,ylab="Inflation Rate",type="l",xlab="Year",cex.lab=1.5,
     cex.axis=1.5,cex.main=1.3,main="(a) Time Series")

plot(diff(y),ylab="Change in Rate",type="l",xlab="Year",cex.lab=1.5,
     cex.axis=1.5,cex.main=1.2,main="(b) Differenced Time Series")



```


Stationary Process: Air Passengers
```{r}
data(AirPassengers)

z = as.ts(AirPassengers, start=1949, frequency=12)

par(mfrow=c(1,1))


plot(z,type="b",ylab="Passengers",cex.axis=1.5,cex.lab=1.5,cex=1.5,lwd=2)

```
Simulating Stationary AR(1) Processes
```{r}
phi = c(0.95, 0.75, 0.2, -0.9)

par(mfrow=c(2,2))

for(i in 1:4){
  y = phi[i]^(0:15)
  plot(0:15, y, xlab="h", ylab=expression(rho(h)), ylim=c(-1,1), type = 'l')
  points(0:15, y, pch = 8)
  text(10, -0.85, eval(substitute(expression(paste(phi," = ",j)), list(j = as.character(phi[i])))), cex = 1.1)
  abline(h=0)     
}



```



Non Stationary AR(1) Processes
```{r}

set.seed(8716)
e = rnorm(200)
x1 = x2 = x3 = x4 = e
for (t in 2:200){
  x1[t] = 0.98*x1[t-1]+e[t]
  x2[t] = -0.6*x2[t-1]+e[t]
  x3[t] = 1.00*x3[t-1]+e[t]
  x4[t] = 1.01*x4[t-1]+e[t]
}

par(mfrow=c(2,2),cex.axis=1.15,cex.lab=1.15,cex.main=1.15)

plot(x1,type="l",xlab="Time (t)",ylab=expression(Y[t]),
     main=expression(paste(phi," = 0.98")))
plot(x2,type="l",xlab="Time (t)",ylab=expression(Y[t]),
     main=expression(paste(phi == - 0.6)))
plot(x3,type="l",xlab="Time (t)",ylab=expression(Y[t]),
     main=expression(paste(phi," = 1")))
plot(x4,type="l",xlab="Time (t)",ylab=expression(Y[t]),
     main=expression(paste(phi," = 1.01")))


```

Simulating an ARMA process
```{r}
arima.sim(n = 63, list(ar = c(0.8897, -0.4858), ma = c(-0.2279, 0.2488)))

plot(arima.sim(n = 63, list(ar = c(0.8897, -0.4858), ma = c(-0.2279, 0.2488))))


```

```{r}
set.seed(123)
arima.sim(n = 10000, list(ar = 0.5))
plot(arima.sim(n = 10000, list(ar = 0.5)))

```


Residuals and Model Checking
```{r}

options(digits=9)

data(bmw, package = "evir")

fitAR1 = arima(bmw, order = c(1,0,0))

library(xts)
plot(xts(residuals(fitAR1), attr(bmw,"times")),main="(a)", minor.ticks = FALSE)

acf(residuals(fitAR1),lag.max=20,main="(b)")
qqnorm(residuals(fitAR1),main="(c)") ; qqline(residuals(fitAR1))


Box.test(residuals(fitAR1), lag = 10, fitdf = 1, type = "Ljung-Box")

fitMA1 = arima(bmw, order = c(0,0,1))
plot(residuals(fitMA1))

acf(residuals(fitMA1))
```



Residuals and Model Checking
```{r}
data(Mishkin, package = "Ecdat")
y = as.vector(Mishkin[,1])

fit = arima(y, order = c(1,0,0))

par(mfrow=c(1,2))
acf(y,main="Inflation rate")
acf(fit$resid,main="Residuals from AR(1)")

```



Miscellaneous - After auto.arima
```{r}
library(tseries)
library(forecast)

y <- arima.sim(list(ar=c(0.5)), n = 1000)

yFit <- arima(y, order=c(0,0,1))

residuals(yFit)

acf(residuals(yFit))

Box.test(residuals(yFit), type="Ljung-Box", lag = 10, fitdf=1)

auto.arima(y)

```
Seasonal Models

```{r}

data(Hstarts, package="Ecdat")

x = ts(Hstarts[,1], start=1960, frequency=4)

fit1 = arima(x, 
             c(1,1,1), 
             seasonal = list(order = c(1,1,1), 
                             period = 4))

fit2 = arima(x, 
             c(1,1,1), 
             seasonal = list(order = c(0,1,1), 
                             period = 4))

Box.test(residuals(fit1), type="Ljung-Box", lag = 10, fitdf=4)

Box.test(residuals(fit2), type="Ljung-Box", lag = 10, fitdf=3)


auto.arima(x, max.P = 0, max.Q = 0)


auto.arima(x, max.p = 0, max.q = 0)

auto.arima(x, max.q = 0)

model1 = arima(bmw, order=c(0,0,2))
forecast1 = predict(model1, n.ahead=8)
plot(forecast1, xlim = , ylim =)



model2 = auto.arima(bmw, ic="bic")
forecast2 = forecast(model2,h=8)
plot(forecast2, xlim = , ylim = )






```
GARCH Modeling
```{r}

library(xts)
library(rugarch)
library(fGarch)

data(bmw, package="evir")

garchFit(formula = ~arma(1, 1) + garch(1, 1), data = bmw, cond.dist = "norm")

garchFit(formula = ~arma(1, 1) + garch(1, 1), data = bmw)






```



```{r}

library(MASS)
bmw.garch.norm <- garchFit(formula = ~arma(1, 0) + garch(1, 1), data = bmw, cond.dist = "norm")

e = residuals(bmw.garch.norm, standardize=TRUE)
fitdistr(e,"t")
n = length(e)
grid = (1:n)/(n+1)

qqplot(sort(as.numeric(e)), qt(grid,df=4),
       main="t-plot, df=4",xlab= "Standardized residual quantiles",
       ylab="t-quantiles")

qqnorm(sort(as.numeric(e))); qqline(y, col = 2)




```


```{r}


garchFit(formula = ~arma(1, 1) + garch(1, 1), data = bmw, cond.dist = "std")



arma.garch.norm = ugarchspec(mean.model=list(armaOrder=c(1,0)),
                             variance.model=list(garchOrder=c(1,1)))
bmw.garch.norm = ugarchfit(data=bmw, spec=arma.garch.norm)
show(bmw.garch.norm)
plot(bmw.garch.norm, which="all")
par(mfrow = c(3,2))
for(i in c(1,3,10,11,8,9)) plot(bmw.garch.norm, which=i)

```

